import type { Knex } from 'knex'

/**
 * Create user_invitations table migration
 * Stores user invitation tokens for multi-tenant invitations
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('user_invitations', (table) => {
    // Primary key - UUID
    // Note: UUID is generated by BaseModel.$beforeInsert() using uuidv4()
    // No database default needed as application handles UUID generation
    table.uuid('id').primary()

    // Foreign keys
    table
      .uuid('user_id')
      .notNullable()
      .references('id')
      .inTable('users')
      .onDelete('CASCADE')
      .comment('User being invited')
    table
      .uuid('tenant_id')
      .notNullable()
      .references('id')
      .inTable('tenants')
      .onDelete('CASCADE')
      .comment('Tenant for which the user is being invited')
    table
      .uuid('role_id')
      .notNullable()
      .references('id')
      .inTable('roles')
      .onDelete('CASCADE')
      .comment('Role to be assigned when invitation is accepted')
    table
      .string('token', 255)
      .notNullable()
      .unique()
      .comment('Unique invitation token')
    table
      .uuid('invited_by')
      .notNullable()
      .references('id')
      .inTable('users')
      .onDelete('CASCADE')
      .comment('User who sent the invitation')

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable()

    // Soft delete (optional, for tracking deleted invitations)
    table.timestamp('deleted_at').nullable()

    // Indexes
    table.index('user_id')
    table.index('tenant_id')
    table.index('invited_by')
    table.index('role_id')
    table.index('token')
    // Composite indexes for common queries
    table.index(['user_id', 'tenant_id']) // For finding invitations by user and tenant
    table.index(['user_id', 'deleted_at']) // For finding active invitations by user
    table.index(['tenant_id', 'deleted_at']) // For finding active invitations by tenant
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('user_invitations')
}
