import type { Knex } from 'knex'

/**
 * Create roles table migration
 * Stores role information for role-based access control
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('roles', (table) => {
    // Primary key - UUID
    // Note: UUID is generated by BaseModel.$beforeInsert() using uuidv4()
    // No database default needed as application handles UUID generation
    table.uuid('id').primary()

    // Role information
    table.string('name', 255).notNullable().unique()
    table.string('display_name', 255).notNullable()
    table.text('description').nullable()
    table.boolean('is_active').defaultTo(true).notNullable()

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable()

    // Soft delete
    table.timestamp('deleted_at').nullable()

    // Indexes
    table.index('name')
    table.index('deleted_at')
    // Composite indexes for common queries
    table.index(['is_active', 'deleted_at']) // For finding active roles
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('roles')
}
