import type { Knex } from 'knex'

/**
 * Create mfa_email_otps table migration
 * Stores temporary email OTP codes for email-based MFA authentication
 * These are short-lived codes (5 minutes) sent via email
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('mfa_email_otps', (table) => {
    // Primary key - UUID
    // Note: UUID is generated by BaseModel.$beforeInsert() using uuidv4()
    // No database default needed as application handles UUID generation
    table.uuid('id').primary()

    // Foreign key to users table
    table
      .uuid('user_id')
      .notNullable()
      .references('id')
      .inTable('users')
      .onDelete('CASCADE')

    // OTP information
    table.string('code', 255).notNullable().unique() // 6-digit OTP code
    table.timestamp('expires_at').notNullable() // Expiry time (5 minutes)

    // Audit/tracking information
    table.string('user_agent', 500).nullable() // Browser/device info
    table.string('ip_address', 45).nullable() // IPv6 can be up to 45 characters

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable()

    // Soft delete (for tracking used/expired codes)
    table.timestamp('deleted_at').nullable()

    // Indexes for performance
    table.index('user_id')
    table.index('code')
    table.index('expires_at')

    // Composite indexes for common queries
    table.index(['expires_at', 'deleted_at']) // For cleaning expired OTP codes
    table.index(['user_id', 'deleted_at']) // For finding active OTP codes by user
    table.index(['user_id', 'code', 'deleted_at']) // For OTP verification
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('mfa_email_otps')
}
