import type { Knex } from 'knex'

/**
 * Create password_resets table migration
 * Stores password reset tokens for users
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('password_resets', (table) => {
    // Primary key - UUID
    // Note: UUID is generated by BaseModel.$beforeInsert() using uuidv4()
    // No database default needed as application handles UUID generation
    table.uuid('id').primary()

    // Password reset information
    table.string('email', 255).notNullable()
    table.string('token', 255).notNullable().unique()
    table.timestamp('expires_at').notNullable()

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable()

    // Soft delete (optional, for tracking deleted tokens)
    table.timestamp('deleted_at').nullable()

    // Indexes
    table.index('email')
    table.index('token')
    table.index('expires_at')
    // Composite indexes for common queries
    table.index(['expires_at', 'deleted_at']) // For cleaning expired tokens
    table.index(['email', 'deleted_at']) // For finding active tokens by email
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('password_resets')
}
