import type { Knex } from 'knex'

/**
 * Create accounts table migration
 * Tenant-specific table for managing bank accounts
 * This migration should only be run in tenant schemas, not in public schema
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('accounts', (table) => {
    // Primary key - UUID
    // Note: UUID is generated by BaseModel.$beforeInsert() using uuidv4()
    // No database default needed as application handles UUID generation
    table.uuid('id').primary()

    // Tenant reference
    table
      .uuid('tenant_id')
      .notNullable()
      .references('id')
      .inTable('public.tenants')
      .onDelete('CASCADE')
      .comment('Reference to the tenant this account belongs to')

    // Created by reference
    table
      .uuid('created_by')
      .notNullable()
      .references('id')
      .inTable('public.users')
      .onDelete('RESTRICT')
      .comment('Reference to the user who created this account')

    // Account information
    table.string('name', 255).notNullable().comment('Account name')
    table.string('number', 255).nullable().comment('Account number')
    table
      .string('type', 255)
      .notNullable()
      .defaultTo('bank')
      .comment('Account type (e.g., bank, cash, credit, investment)')
    table
      .string('currency_code', 3)
      .notNullable()
      .defaultTo('CAD')
      .comment('ISO 4217 currency code (e.g., CAD, USD, EUR, GBP)')

    // Financial information
    table
      .decimal('opening_balance', 15, 2)
      .defaultTo(0)
      .notNullable()
      .comment('Opening balance of the account')

    table
      .decimal('current_balance', 15, 2)
      .defaultTo(0)
      .notNullable()
      .comment('Current balance (updated from transactions)')

    // Bank information
    table.string('bank_name', 255).nullable().comment('Name of the bank')

    // Reconciliation fields
    table
      .timestamp('last_reconciled_at')
      .nullable()
      .comment('Last reconciliation date')

    table
      .decimal('reconciled_balance', 15, 2)
      .nullable()
      .comment('Balance at last reconciliation')

    table
      .uuid('last_reconciled_by')
      .nullable()
      .references('id')
      .inTable('public.users')
      .onDelete('SET NULL')
      .comment('User who performed last reconciliation')

    // Account status
    table
      .boolean('is_active')
      .defaultTo(true)
      .notNullable()
      .comment('Whether the account is active')

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable()

    // Soft delete
    table.timestamp('deleted_at').nullable()

    // Indexes
    table.index('tenant_id')
    table.index('created_by')
    table.index('is_active')
    table.index('deleted_at')
    // Composite indexes for common queries
    table.index(['tenant_id', 'is_active']) // For finding active accounts by tenant
    table.index(['tenant_id', 'deleted_at']) // For finding active accounts by tenant
    table.index(['created_by', 'tenant_id']) // For finding accounts created by a user in a tenant
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('accounts')
}
