import type { Knex } from 'knex'

/**
 * Create tax_exemptions table migration
 * Tenant-specific table for tax exemption configurations
 * Tax exemptions allow marking customers/vendors as tax-exempt
 * This migration should only be run in tenant schemas, not in public schema
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('tax_exemptions', (table) => {
    // Primary key - UUID
    // Note: UUID is generated by BaseModel.$beforeInsert() using uuidv4()
    // No database default needed as application handles UUID generation
    table.uuid('id').primary()

    // Tenant reference
    table
      .uuid('tenant_id')
      .notNullable()
      .references('id')
      .inTable('public.tenants')
      .onDelete('CASCADE')
      .comment('Reference to the tenant this tax exemption belongs to')

    // Contact reference (customer or vendor)
    // Note: This references a future contacts table. For now, it's a UUID that can be linked later
    table
      .uuid('contact_id')
      .notNullable()
      .comment(
        'Reference to the contact (customer/vendor) this exemption applies to'
      )

    // Tax reference (null = exemption applies to all taxes)
    table
      .uuid('tax_id')
      .nullable()
      .references('id')
      .inTable('taxes')
      .onDelete('CASCADE')
      .comment('Specific tax exemption (null = all taxes)')

    // Exemption details
    table
      .string('exemption_type', 50)
      .notNullable()
      .defaultTo('resale')
      .comment('Exemption type: resale, non_profit, government, other')

    table
      .string('certificate_number', 255)
      .nullable()
      .comment('Tax exemption certificate number')

    table
      .date('certificate_expiry')
      .nullable()
      .comment('Certificate expiry date (null = no expiry)')

    table.text('reason').nullable().comment('Reason for exemption')

    table
      .boolean('is_active')
      .notNullable()
      .defaultTo(true)
      .comment('Whether this exemption is active')

    // Audit fields
    table
      .uuid('created_by')
      .notNullable()
      .references('id')
      .inTable('public.users')
      .onDelete('RESTRICT')
      .comment('User who created this tax exemption')

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('deleted_at').nullable()

    // Indexes
    table.index(
      ['tenant_id', 'deleted_at'],
      'idx_tax_exemptions_tenant_deleted'
    )
    table.index(
      ['tenant_id', 'contact_id'],
      'idx_tax_exemptions_tenant_contact'
    )
    table.index(['tenant_id', 'tax_id'], 'idx_tax_exemptions_tenant_tax')
    table.index(['tenant_id', 'is_active'], 'idx_tax_exemptions_tenant_active')
    table.index(['certificate_expiry'], 'idx_tax_exemptions_expiry')
  })

  // Note: updated_at is handled by BaseModel.$beforeUpdate() hook at application level
  // No database trigger needed - matches pattern used in other migrations
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('tax_exemptions')
}
