import type { Knex } from 'knex'

/**
 * Create taxes table migration
 * Tenant-specific table for tax rate configurations
 * Supports normal, compound, and withholding tax types
 * This migration should only be run in tenant schemas, not in public schema
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('taxes', (table) => {
    // Primary key - UUID
    // Note: UUID is generated by BaseModel.$beforeInsert() using uuidv4()
    // No database default needed as application handles UUID generation
    table.uuid('id').primary()

    // Tenant reference
    table
      .uuid('tenant_id')
      .notNullable()
      .references('id')
      .inTable('public.tenants')
      .onDelete('CASCADE')
      .comment('Reference to the tenant this tax belongs to')

    // Tax fields
    table
      .string('name', 255)
      .notNullable()
      .comment('Tax name (e.g., "GST", "VAT", "Sales Tax")')

    table
      .string('type', 50)
      .notNullable()
      .defaultTo('normal')
      .comment('Tax type: normal, compound, withholding')

    table
      .decimal('rate', 15, 4)
      .notNullable()
      .comment('Tax rate (e.g., 10.00 for 10%)')

    table
      .boolean('is_active')
      .notNullable()
      .defaultTo(true)
      .comment('Whether this tax is active')

    // Audit fields
    table
      .uuid('created_by')
      .notNullable()
      .references('id')
      .inTable('public.users')
      .onDelete('RESTRICT')
      .comment('User who created this tax')

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('deleted_at').nullable()

    // Indexes
    table.index(['tenant_id', 'deleted_at'], 'idx_taxes_tenant_deleted')
    table.index(['tenant_id', 'is_active'], 'idx_taxes_tenant_active')
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('taxes')
}
