import type { Knex } from 'knex'

/**
 * Create chart_of_accounts table migration
 * Tenant-specific table for Chart of Accounts (General Ledger)
 * Foundation for proper double-entry accounting
 * This migration should only be run in tenant schemas, not in public schema
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('chart_of_accounts', (table) => {
    // Primary key - UUID
    // Note: UUID is generated by BaseModel.$beforeInsert() using uuidv4()
    // No database default needed as application handles UUID generation
    table.uuid('id').primary()

    // Tenant reference
    table
      .uuid('tenant_id')
      .notNullable()
      .references('id')
      .inTable('public.tenants')
      .onDelete('CASCADE')
      .comment('Reference to the tenant this account belongs to')

    // Created by reference
    table
      .uuid('created_by')
      .notNullable()
      .references('id')
      .inTable('public.users')
      .onDelete('RESTRICT')
      .comment('Reference to the user who created this account')

    // Account identification
    table
      .string('account_number', 50)
      .nullable()
      .comment('Account number (e.g., 1000, 1100, 2000)')

    table
      .string('account_name', 255)
      .notNullable()
      .comment('Account name (e.g., Cash, Accounts Receivable)')

    // Account classification
    table
      .string('account_type', 50)
      .notNullable()
      .comment('Account type: asset, liability, equity, revenue, expense')

    table
      .string('account_subtype', 100)
      .nullable()
      .comment('Account subtype (e.g., current_asset, fixed_asset, etc.)')

    table
      .string('account_detail_type', 100)
      .nullable()
      .comment('Detailed classification (e.g., checking, savings, etc.)')

    // Hierarchical structure
    table
      .uuid('parent_account_id')
      .nullable()
      .references('id')
      .inTable('chart_of_accounts')
      .onDelete('SET NULL')
      .comment('Parent account ID for hierarchical structure')

    // Balance tracking
    table
      .decimal('current_balance', 15, 4)
      .notNullable()
      .defaultTo(0)
      .comment('Current balance of the account')

    table
      .decimal('opening_balance', 15, 4)
      .notNullable()
      .defaultTo(0)
      .comment('Opening balance when account was created')

    // Account properties
    table
      .boolean('is_active')
      .notNullable()
      .defaultTo(true)
      .comment('Whether the account is active')

    table
      .boolean('is_system_account')
      .notNullable()
      .defaultTo(false)
      .comment('System accounts cannot be deleted')

    table
      .string('currency_code', 3)
      .notNullable()
      .defaultTo('CAD')
      .comment('ISO 4217 currency code')

    // Description
    table.text('description').nullable().comment('Account description')

    // Tax tracking
    table
      .boolean('track_tax')
      .notNullable()
      .defaultTo(false)
      .comment('Whether to track tax for this account')

    table
      .uuid('default_tax_id')
      .nullable()
      .comment('Default tax ID for this account')

    // Bank account specific (for asset accounts)
    table
      .string('bank_account_number', 100)
      .nullable()
      .comment('Bank account number if this is a bank account')

    table
      .string('bank_routing_number', 50)
      .nullable()
      .comment('Bank routing number if this is a bank account')

    // Link to bank account (accounts table)
    table
      .uuid('bank_account_id')
      .nullable()
      .references('id')
      .inTable('accounts')
      .onDelete('SET NULL')
      .comment(
        'Link to bank account if this chart account represents a bank account'
      )

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable()

    // Soft delete
    table.timestamp('deleted_at').nullable()

    // Indexes
    table.index('tenant_id')
    table.index('created_by')
    table.index('account_type')
    table.index('parent_account_id')
    table.index('is_active')
    table.index('deleted_at')

    // Composite indexes for common queries
    table.index(['tenant_id', 'deleted_at']) // For finding active accounts by tenant
    table.index(['tenant_id', 'account_type']) // For filtering by account type
    table.index(['tenant_id', 'parent_account_id']) // For finding children of parent account
    table.index(['tenant_id', 'is_active', 'deleted_at']) // For finding active accounts
    table.index('bank_account_id') // For linking to bank accounts

    // Unique constraint: account_number must be unique per tenant (excluding deleted)
    // Note: This allows same account_number for different tenants and soft-deleted accounts
    table.unique(['tenant_id', 'account_number', 'deleted_at'])
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('chart_of_accounts')
}
