import type { Knex } from 'knex'

/**
 * Create account_balance_history table migration
 * Tenant-specific table for tracking Chart of Accounts balance changes over time
 * Provides complete audit trail of all balance updates from journal entries and transactions
 * This migration should only be run in tenant schemas, not in public schema
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('account_balance_history', (table) => {
    // Primary key - UUID
    // Note: UUID is generated by BaseModel.$beforeInsert() using uuidv4()
    // No database default needed as application handles UUID generation
    table.uuid('id').primary()

    // Tenant reference
    table
      .uuid('tenant_id')
      .notNullable()
      .references('id')
      .inTable('public.tenants')
      .onDelete('CASCADE')
      .comment('Reference to the tenant this balance history belongs to')

    // Account reference
    table
      .uuid('account_id')
      .notNullable()
      .references('id')
      .inTable('chart_of_accounts')
      .onDelete('CASCADE')
      .comment('Reference to the chart of account whose balance changed')

    // Source of balance change
    table
      .uuid('journal_entry_id')
      .nullable()
      .references('id')
      .inTable('journal_entries')
      .onDelete('SET NULL')
      .comment('Journal entry that caused this balance change')

    table
      .uuid('journal_entry_line_id')
      .nullable()
      .references('id')
      .inTable('journal_entry_lines')
      .onDelete('SET NULL')
      .comment('Specific journal entry line that caused this balance change')

    // Balance information
    table
      .decimal('previous_balance', 15, 4)
      .notNullable()
      .defaultTo(0)
      .comment('Account balance before this change')

    table
      .decimal('new_balance', 15, 4)
      .notNullable()
      .defaultTo(0)
      .comment('Account balance after this change')

    table
      .decimal('change_amount', 15, 4)
      .notNullable()
      .defaultTo(0)
      .comment('Amount of the change (absolute value)')

    table
      .string('change_type', 20)
      .notNullable()
      .comment('Type of change: debit or credit')

    // Change details
    table
      .timestamp('change_date')
      .notNullable()
      .defaultTo(knex.fn.now())
      .comment('Date and time when the balance change occurred')

    table
      .text('description')
      .nullable()
      .comment('Description of the balance change')

    // Source tracking (for future transactions feature)
    table
      .string('source_module', 100)
      .nullable()
      .comment('Source module: journal_entries, transactions, etc.')

    table
      .uuid('source_id')
      .nullable()
      .comment('ID of the source record (journal entry, transaction, etc.)')

    // Audit fields
    table
      .uuid('created_by')
      .notNullable()
      .references('id')
      .inTable('public.users')
      .onDelete('RESTRICT')
      .comment('User who triggered this balance change')

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('deleted_at').nullable()

    // Indexes for efficient querying
    table.index(
      ['tenant_id', 'account_id', 'change_date'],
      'idx_balance_history_account_date'
    )
    table.index(
      ['tenant_id', 'journal_entry_id'],
      'idx_balance_history_journal_entry'
    )
    table.index(['tenant_id', 'change_date'], 'idx_balance_history_date')
    table.index(
      ['account_id', 'change_date'],
      'idx_balance_history_account_date_only'
    )
    table.index(['tenant_id', 'deleted_at'], 'idx_balance_history_deleted_at')
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('account_balance_history')
}
