/**
 * Success Messages
 * Standardized success messages used across the application
 */
export const SUCCESS_MESSAGES = {
  USER_REGISTERED: 'User registered successfully',
  LOGIN_SUCCESSFUL: 'Login successful',
  LOGOUT_SUCCESSFUL: 'Logout successful',
  TOKEN_REFRESHED: 'Token refreshed successfully',
  PASSWORD_RESET_EMAIL_SENT:
    'If the email exists, a password reset link has been sent',
  PASSWORD_RESET_SUCCESSFUL: 'Password reset successful',
  USER_PROFILE_RETRIEVED: 'User profile retrieved successfully',
  USER_PROFILE_UPDATED: 'User profile updated successfully',
  USERS_RETRIEVED: 'Users retrieved successfully',
  USER_RETRIEVED: 'User retrieved successfully',
  USER_DELETED: 'User deleted successfully',
  USER_RESTORED: 'User restored successfully',
  USER_ROLES_UPDATED: 'User roles updated successfully',
  USER_INVITED: 'User invitation sent successfully',
  INVITATION_VERIFIED: 'Invitation verified successfully',
  INVITATION_ACCEPTED: 'Invitation accepted successfully',
  INVITATION_REVOKED: 'Invitation revoked successfully',
  INVITATION_RESENT: 'Invitation email resent successfully',
  INVITATIONS_RETRIEVED: 'Invitations retrieved successfully',
  USER_ACTIVATED: 'User account activated successfully',
  USER_DEACTIVATED: 'User account deactivated successfully',
  USER_STATISTICS_RETRIEVED: 'User statistics retrieved successfully',
  PASSWORD_CHANGED: 'Password changed successfully',
  ROLES_RETRIEVED: 'Roles retrieved successfully',
  ROLE_RETRIEVED: 'Role retrieved successfully',
  ROLE_STATISTICS_RETRIEVED: 'Role statistics retrieved successfully',
  ROLE_WITH_PERMISSIONS_RETRIEVED:
    'Role with permissions retrieved successfully',
  ROLE_PERMISSIONS_UPDATED: 'Role permissions updated successfully',
  MFA_OTP_SENT: 'Verification code sent to your email',
  MFA_VERIFIED: 'Multi-factor authentication successful',
  MFA_ENABLED: 'Email OTP MFA enabled successfully',
  MFA_DISABLED: 'Email OTP MFA disabled successfully',
  MFA_STATUS_RETRIEVED: 'MFA status retrieved successfully',
  MFA_TOTP_SETUP_INITIATED: 'TOTP authenticator setup initiated',
  MFA_TOTP_ENABLED: 'TOTP authenticator enabled successfully',
  MFA_TOTP_DISABLED: 'TOTP authenticator disabled successfully',
  MFA_TOTP_VERIFIED: 'TOTP code verified successfully',
  TOTP_STATUS_RETRIEVED: 'TOTP status retrieved successfully',
  MFA_BACKUP_CODES_GENERATED: 'Backup codes generated successfully',
  TENANTS_RETRIEVED: 'Tenants retrieved successfully',
  TENANT_RETRIEVED: 'Tenant retrieved successfully',
  TENANT_ONBOARDED: 'Tenant onboarded successfully',
  TENANT_UPDATED: 'Tenant updated successfully',
  TENANT_DELETED: 'Tenant deleted successfully',
  TENANT_RESTORED: 'Tenant restored successfully',
  TENANT_SWITCHED: 'Tenant switched successfully',
  ACCOUNTS_RETRIEVED: 'Accounts retrieved successfully',
  ACCOUNT_RETRIEVED: 'Account retrieved successfully',
  ACCOUNT_CREATED: 'Account created successfully',
  ACCOUNT_UPDATED: 'Account updated successfully',
  ACCOUNT_DELETED: 'Account deleted successfully',
  ACCOUNT_RESTORED: 'Account restored successfully',
  ACCOUNT_ACTIVATED: 'Account activated successfully',
  ACCOUNT_DEACTIVATED: 'Account deactivated successfully',
  ACCOUNT_STATUS_RETRIEVED: 'Account status retrieved successfully',
  AUDIT_LOGS_RETRIEVED: 'Audit logs retrieved successfully',
  AUDIT_LOG_RETRIEVED: 'Audit log retrieved successfully',
  PASSKEY_REGISTRATION_OPTIONS_GENERATED:
    'Passkey registration options generated successfully',
  PASSKEY_REGISTERED: 'Passkey registered successfully',
  PASSKEY_AUTHENTICATION_OPTIONS_GENERATED:
    'Passkey authentication options generated successfully',
  PASSKEY_AUTHENTICATED: 'Passkey authentication successful',
  PASSKEY_RETRIEVED: 'Passkey retrieved successfully',
  PASSKEYS_RETRIEVED: 'Passkeys retrieved successfully',
  PASSKEY_RENAMED: 'Passkey renamed successfully',
  PASSKEY_DELETED: 'Passkey deleted successfully',
  PASSKEY_ACTIVATED: 'Passkey activated successfully',
  PASSKEY_DEACTIVATED: 'Passkey deactivated successfully',
  PASSKEY_STATS_RETRIEVED: 'Passkey statistics retrieved successfully',
  CHART_OF_ACCOUNT_CREATED: 'Chart of account created successfully',
  CHART_OF_ACCOUNT_UPDATED: 'Chart of account updated successfully',
  CHART_OF_ACCOUNT_DELETED: 'Chart of account deleted successfully',
  CHART_OF_ACCOUNT_FETCHED: 'Chart of account fetched successfully',
  CHART_OF_ACCOUNTS_FETCHED: 'Chart of accounts fetched successfully',
  CHART_OF_ACCOUNT_ENABLED: 'Chart of account enabled successfully',
  CHART_OF_ACCOUNT_DISABLED: 'Chart of account disabled successfully',
  CHART_OF_ACCOUNT_SAMPLE_DOWNLOADED:
    'Chart of account sample file downloaded successfully',
  CHART_OF_ACCOUNT_IMPORT_FIELDS_FETCHED:
    'Chart of accounts import fields retrieved successfully',
  JOURNAL_ENTRY_CREATED: 'Journal entry created successfully',
  JOURNAL_ENTRY_UPDATED: 'Journal entry updated successfully',
  JOURNAL_ENTRY_DELETED: 'Journal entry deleted successfully',
  JOURNAL_ENTRY_FETCHED: 'Journal entry fetched successfully',
  JOURNAL_ENTRIES_FETCHED: 'Journal entries fetched successfully',
  JOURNAL_ENTRY_POSTED: 'Journal entry posted successfully',
  JOURNAL_ENTRY_VOIDED: 'Journal entry voided successfully',
  JOURNAL_ENTRY_RESTORED: 'Journal entry restored successfully',
  JOURNAL_ENTRY_REVERSED: 'Journal entry reversed successfully',
  JOURNAL_ENTRY_DUPLICATED: 'Journal entry duplicated successfully',
  BALANCE_HISTORY_FETCHED: 'Balance history retrieved successfully',
  BALANCE_HISTORY_LIST_FETCHED: 'Balance history list retrieved successfully',
  TAX_CREATED: 'Tax created successfully',
  TAX_UPDATED: 'Tax updated successfully',
  TAX_DELETED: 'Tax deleted successfully',
  TAX_FETCHED: 'Tax retrieved successfully',
  TAXES_FETCHED: 'Taxes retrieved successfully',
  TAX_RESTORED: 'Tax restored successfully',
  TAX_ENABLED: 'Tax enabled successfully',
  TAX_DISABLED: 'Tax disabled successfully',
  TAX_STATUS_RETRIEVED: 'Tax status retrieved successfully',
  TAX_STATISTICS_RETRIEVED: 'Tax statistics retrieved successfully',
  TAX_GROUP_CREATED: 'Tax group created successfully',
  TAX_GROUP_UPDATED: 'Tax group updated successfully',
  TAX_GROUP_DELETED: 'Tax group deleted successfully',
  TAX_GROUP_FETCHED: 'Tax group retrieved successfully',
  TAX_GROUPS_FETCHED: 'Tax groups retrieved successfully',
  TAX_GROUP_RESTORED: 'Tax group restored successfully',
  TAX_GROUP_ENABLED: 'Tax group enabled successfully',
  TAX_GROUP_DISABLED: 'Tax group disabled successfully',
  TAX_GROUP_CALCULATED: 'Tax calculation completed successfully',
  TAX_EXEMPTION_CREATED: 'Tax exemption created successfully',
  TAX_EXEMPTION_UPDATED: 'Tax exemption updated successfully',
  TAX_EXEMPTION_DELETED: 'Tax exemption deleted successfully',
  TAX_EXEMPTION_FETCHED: 'Tax exemption retrieved successfully',
  TAX_EXEMPTIONS_FETCHED: 'Tax exemptions retrieved successfully',
  TAX_EXEMPTION_RESTORED: 'Tax exemption restored successfully',
  TAX_EXEMPTION_ENABLED: 'Tax exemption enabled successfully',
  TAX_EXEMPTION_DISABLED: 'Tax exemption disabled successfully',
} as const
